# For more information, see:
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml

runtime: nodejs
service: example
env: flex

runtime_config:
  operating_system: "ubuntu22"
beta_settings:
  cloud_sql_instances: livitay:europe-west2:livitay
liveness_check:
  check_interval_sec: 120
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
readiness_check:
  check_interval_sec: 20
  timeout_sec: 5
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5
env_variables:
  FOO: BAR
